### ISSUE TITLE
unable to print/parse empty string attribute values

### ISSUE THREAD

**Issue by vortextangent** [watoki/dom#1]
When an html document node's attribute is an empty string the parser does not set the value to an empty string.

I changed the printer test to illustrate the bug.

```
There was 1 failure:

1) spec\watoki\dom\PrinterTest::testAttributes
    Failed asserting that two strings are equal.
    --- Expected
    +++ Actual
    @@ @@
    -'<element empty emptyquote="" unquoted=value single='quoted' quoted="value"/>'
    +'<element empty emptyquote unquoted=value single='quoted' quoted="value"/>'
```

I have a proposed fix in the attached pull request
#2

**Comment by theseer** [comment]
Would you mind making a new release for this fix?
